### ISSUE TITLE
Assignment checklist

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#195]
A rubric can be one of three types: normal (avg x), bonus (+x) or penalty (-x). 

Some rubrics we could think of:
- [ ] Check that students have added a report to their submission
- [ ] Check that students have attached a commit to their submission
- [ ] Ability to set a threshold for the amount of generated Checkstyle warnings
- [ ] Ability to set a threshold for the amount of generated PMD / Findbugs warnings
- [ ] Ability to set a threshold for the amount of generated Git usage warnings
- [ ] Too late delivery penalty (as a function of time)
- [ ] Verify usage of pull requests
- [ ] Rubrics that should be checked manually. Ability to add descriptions to the rubric.
- [ ] Ability to group rubrics together.
